### PR TITLE
Fix data serialization test

### LINKED ISSUE #140: Fix test failures in DatasetSerializationTest
These tests started failing in the past couple weeks when run locally, though oddly enough did not fail when run against CircleCI.

### PR DESCRIPTION
**Pull request by sshah-wework**
Parses the timestamps with a timezone-aware date format.

Closes #140

### CODE REVIEW

File: src/test/java/marquez/api/DatasetSerializationTest.java [hunk 1]
```diff
@@ -21,24 +20,23 @@
...
+          new Dataset(
+              "sample_dataset",
+              createdAt,
+              updatedAt,
+              Dataset.Type.DB_TABLE,
+              Dataset.Origin.EXTERNAL,
+              UUID.fromString("10892965-454c-4bb1-b187-d67f2141423c"),
+              "sample dataset for testing");
+    } catch (ParseException e) {
+      System.out.println(e.getMessage());
```
Comment (ashulmanWeWork) [inline src/test/java/marquez/api/DatasetSerializationTest.java]: You'd want to fail the test here.

Comment (sshah-wework) [reply src/test/java/marquez/api/DatasetSerializationTest.java]: good call
