### PR TITLE
fix dataset list error

### LINKED ISSUE #265: Listing datasets in a namespace returns an error
```
$ ./datasets.py --list --namespace=demo
{"code":500,"message":"There was an error processing your request. It has been logged (ID 8205e8e99febd37c)."}
```

### PR DESCRIPTION
**Pull request by sshah-wework**
Fixes #265

### CODE REVIEW

File: src/main/java/marquez/db/DatasetDao.java [hunk 1]
```diff
@@ -57,9 +56,14 @@ void updateCurrentVersion(
...
 
-  @SqlQuery("SELECT * FROM datasets LIMIT :limit OFFSET :offset")
+  @SqlQuery(
+      "SELECT * "
+          + "FROM datasets d "
+          + "INNER JOIN namespaces n "
+          + "     ON (n.guid = d.namespace_guid AND n.name=:namespace)"
+          + "LIMIT :limit OFFSET :offset")
   List<DatasetRow> findAll(
-      @Bind("namespace") Namespace namespace,
```
Comment (wslulciuc) [inline src/main/java/marquez/db/DatasetDao.java]: We can still use our defined types here using `@BindBean` instead `@Bind` (which only supports primitive types, `UUID`, etc)

Comment (sshah-wework) [reply src/main/java/marquez/db/DatasetDao.java]: ah, right. switching to `@BindBean`

File: src/test/java/marquez/db/DatasetDaoTest.java [hunk 2]
```diff
@@ -0,0 +1,67 @@
...
+
+  @Before
+  public void setup() {
+    Jdbi jdbi = dbRule.getJdbi();
+    datasetDAO = jdbi.onDemand(DatasetDao.class);
+    namespaceDAO = jdbi.onDemand(NamespaceDao.class);
+    namespaceDAO.insert(namespace);
+  }
+
+  @After
```
Comment (sshah-wework) [inline src/test/java/marquez/db/DatasetDaoTest.java]: won't need this if the `JdbiRule` is not a class rule

File: src/test/java/marquez/core/models/Generator.java [hunk 3]
```diff
@@ -123,11 +133,52 @@ public static Namespace cloneNamespace(Namespace n) {
...
   public static RunArgs cloneRunArgs(RunArgs ra) {
     return new RunArgs(ra.getHexDigest(), ra.getJson(), ra.getCreatedAt());
   }
+
+  // Data Source Rows
+  public static DataSourceRow genDataSourceRow() {
+    int dataSourceNum = randNum();
+    return DataSourceRow.builder()
+        .uuid(UUID.randomUUID())
+        .name("Data Source" + dataSourceNum)
```
Comment (ashulmanWeWork) [inline src/test/java/marquez/core/models/Generator.java]: maybe a space after `Source`?

File: src/test/java/marquez/db/DatasetDaoTest.java [hunk 4]
```diff
@@ -0,0 +1,54 @@
...
+import org.junit.Before;
+import org.junit.Rule;
+import org.junit.Test;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+public class DatasetDaoTest {
+  static final Logger logger = LoggerFactory.getLogger(DatasetDaoTest.class);
+  private DatasetDao datasetDAO;
+  private marquez.core.models.Namespace namespace = Generator.genNamespace();
```
Comment (ashulmanWeWork) [inline src/test/java/marquez/db/DatasetDaoTest.java]: can we make this final?

File: src/test/java/marquez/db/DatasetDaoTest.java [hunk 5]
```diff
@@ -0,0 +1,54 @@
...
+  private NamespaceDao namespaceDAO;
+
+  @Rule
+  public final JdbiRule dbRule =
+      JdbiRule.embeddedPostgres().withPlugin(new SqlObjectPlugin()).migrateWithFlyway();
+
+  @Before
```
Comment (ashulmanWeWork) [inline src/test/java/marquez/db/DatasetDaoTest.java]: Can we set these on a per-class basis instead of a per-test-method instance? If so, we can use `@BeforeClass` instead of `@Before`.

File: src/main/java/marquez/api/resources/DatasetResource.java [hunk 6]
```diff
@@ -52,9 +53,13 @@ public Response list(
...
-        datasetService.getAll(Namespace.of(namespaceString), limit, offset);
-    final List<DatasetResponse> datasetResponses = map(datasets);
-    return Response.ok(new DatasetsResponse(datasetResponses)).build();
+    try {
+      final List<Dataset> datasets =
+          datasetService.getAll(Namespace.of(namespaceString), limit, offset);
+      final List<DatasetResponse> datasetResponses = map(datasets);
+      return Response.ok(new DatasetsResponse(datasetResponses)).build();
+    } catch (Exception e) {
+      throw new InternalServerErrorException("unexpected error while fetching datasets", e);
```
Comment (wslulciuc) [inline src/main/java/marquez/api/resources/DatasetResource.java]: 💯

File: src/test/java/marquez/core/models/Generator.java (hunk 3 above)
Comment (sshah-wework) [reply src/test/java/marquez/core/models/Generator.java]: this is just test data

File: src/test/java/marquez/db/DatasetDaoTest.java [hunk 7]
```diff
@@ -0,0 +1,54 @@
...
+import org.jdbi.v3.sqlobject.SqlObjectPlugin;
+import org.jdbi.v3.testing.JdbiRule;
+import org.junit.Before;
+import org.junit.Rule;
+import org.junit.Test;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
+
+public class DatasetDaoTest {
+  static final Logger logger = LoggerFactory.getLogger(DatasetDaoTest.class);
```
Comment (wslulciuc) [inline src/test/java/marquez/db/DatasetDaoTest.java]: minor: the logger's not used? so we can remove
